tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Manage multiple Node.js versions
brew "nvm"
# 📦🚀 Fast, disk space efficient package manager
brew "pnpm"
# Cross-shell prompt for astronauts
brew "spaceship"
# JavaScript package manager
brew "yarn"
# UNIX shell (command interpreter)
brew "zsh"
# Enable Windows-like alt-tab
cask "alt-tab"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Reimagine your terminal
cask "fig"
# Collaborative team software
cask "figma"
# Free monospaced font with programming ligatures
cask "font-fira-code"
cask "font-inconsolata-for-powerline"
# Web browser
cask "google-chrome"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# App to write, plan, collaborate, and get organized
cask "notion"
# Collaboration platform for API development
cask "postman"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Keyboard and mouse configuration tool
cask "steelseries-gg"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Desktop client for WhatsApp
cask "whatsapp"
